# Generated by carnix 0.9.8: carnix generate-nix --src ../.
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
  crates = cratesIO // rec {
# shen-rust-0.0.1

    crates.shen_rust."0.0.1" = deps: { features?(features_.shen_rust."0.0.1" deps {}) }: buildRustCrate {
      crateName = "shen-rust";
      version = "0.0.1";
      authors = [ "aditya.siram@gmail.com" ];
      src = exclude [ ".git" "target" ] ./.;
      dependencies = mapFeatures features ([
        (cratesIO.crates."aster"."${deps."shen_rust"."0.0.1"."aster"}" deps)
        (cratesIO.crates."libc"."${deps."shen_rust"."0.0.1"."libc"}" deps)
        (cratesIO.crates."nom"."${deps."shen_rust"."0.0.1"."nom"}" deps)
        (cratesIO.crates."quasi"."${deps."shen_rust"."0.0.1"."quasi"}" deps)
        (cratesIO.crates."ref_eq"."${deps."shen_rust"."0.0.1"."ref_eq"}" deps)
        (cratesIO.crates."syntex"."${deps."shen_rust"."0.0.1"."syntex"}" deps)
        (cratesIO.crates."syntex_syntax"."${deps."shen_rust"."0.0.1"."syntex_syntax"}" deps)
        (cratesIO.crates."time"."${deps."shen_rust"."0.0.1"."time"}" deps)
        (cratesIO.crates."uuid"."${deps."shen_rust"."0.0.1"."uuid"}" deps)
      ]);
    };
    features_.shen_rust."0.0.1" = deps: f: updateFeatures f (rec {
      aster = fold recursiveUpdate {} [
        { "${deps.shen_rust."0.0.1".aster}"."with-syntex" = true; }
        { "${deps.shen_rust."0.0.1".aster}".default = true; }
      ];
      libc."${deps.shen_rust."0.0.1".libc}".default = true;
      nom."${deps.shen_rust."0.0.1".nom}".default = true;
      quasi = fold recursiveUpdate {} [
        { "${deps.shen_rust."0.0.1".quasi}"."with-syntex" = true; }
        { "${deps.shen_rust."0.0.1".quasi}".default = true; }
      ];
      ref_eq."${deps.shen_rust."0.0.1".ref_eq}".default = true;
      shen_rust."0.0.1".default = (f.shen_rust."0.0.1".default or true);
      syntex."${deps.shen_rust."0.0.1".syntex}".default = true;
      syntex_syntax."${deps.shen_rust."0.0.1".syntex_syntax}".default = true;
      time."${deps.shen_rust."0.0.1".time}".default = true;
      uuid = fold recursiveUpdate {} [
        { "${deps.shen_rust."0.0.1".uuid}"."v4" = true; }
        { "${deps.shen_rust."0.0.1".uuid}".default = true; }
      ];
    }) [
      (cratesIO.features_.aster."${deps."shen_rust"."0.0.1"."aster"}" deps)
      (cratesIO.features_.libc."${deps."shen_rust"."0.0.1"."libc"}" deps)
      (cratesIO.features_.nom."${deps."shen_rust"."0.0.1"."nom"}" deps)
      (cratesIO.features_.quasi."${deps."shen_rust"."0.0.1"."quasi"}" deps)
      (cratesIO.features_.ref_eq."${deps."shen_rust"."0.0.1"."ref_eq"}" deps)
      (cratesIO.features_.syntex."${deps."shen_rust"."0.0.1"."syntex"}" deps)
      (cratesIO.features_.syntex_syntax."${deps."shen_rust"."0.0.1"."syntex_syntax"}" deps)
      (cratesIO.features_.time."${deps."shen_rust"."0.0.1"."time"}" deps)
      (cratesIO.features_.uuid."${deps."shen_rust"."0.0.1"."uuid"}" deps)
    ];


# end

  };

  shen_rust = crates.crates.shen_rust."0.0.1" deps;
  __all = [ (shen_rust {}) ];
  deps.aster."0.25.0" = {
    syntex_syntax = "0.42.0";
  };
  deps.bitflags."0.5.0" = {};
  deps.cfg_if."0.1.9" = {};
  deps.fuchsia_cprng."0.1.1" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.libc."0.2.60" = {};
  deps.log."0.3.9" = {
    log = "0.4.7";
  };
  deps.log."0.4.7" = {
    cfg_if = "0.1.9";
  };
  deps.nom."1.2.4" = {};
  deps.quasi."0.18.0" = {
    syntex_errors = "0.42.0";
    syntex_syntax = "0.42.0";
  };
  deps.rand."0.3.23" = {
    libc = "0.2.60";
    rand = "0.4.6";
  };
  deps.rand."0.4.6" = {
    rand_core = "0.3.1";
    rdrand = "0.4.0";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.56" = {};
  deps.ref_eq."1.0.0" = {};
  deps.rustc_serialize."0.3.24" = {};
  deps.shen_rust."0.0.1" = {
    aster = "0.25.0";
    libc = "0.2.60";
    nom = "1.2.4";
    quasi = "0.18.0";
    ref_eq = "1.0.0";
    syntex = "0.42.2";
    syntex_syntax = "0.42.0";
    time = "0.1.42";
    uuid = "0.2.3";
  };
  deps.syntex."0.42.2" = {
    syntex_errors = "0.42.0";
    syntex_syntax = "0.42.0";
  };
  deps.syntex_errors."0.42.0" = {
    libc = "0.2.60";
    log = "0.3.9";
    rustc_serialize = "0.3.24";
    syntex_pos = "0.42.0";
    term = "0.4.6";
    unicode_xid = "0.0.3";
  };
  deps.syntex_pos."0.42.0" = {
    rustc_serialize = "0.3.24";
  };
  deps.syntex_syntax."0.42.0" = {
    bitflags = "0.5.0";
    libc = "0.2.60";
    log = "0.3.9";
    rustc_serialize = "0.3.24";
    syntex_errors = "0.42.0";
    syntex_pos = "0.42.0";
    term = "0.4.6";
    unicode_xid = "0.0.3";
  };
  deps.term."0.4.6" = {
    kernel32_sys = "0.2.2";
    winapi = "0.2.8";
  };
  deps.time."0.1.42" = {
    libc = "0.2.60";
    redox_syscall = "0.1.56";
    winapi = "0.3.7";
  };
  deps.unicode_xid."0.0.3" = {};
  deps.uuid."0.2.3" = {
    rand = "0.3.23";
  };
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
}
